name: João Marques Teixeira
favicon: null
layout_spectrum: 0.71771
typography_spectrum: 0.600856450619176
title: 'Paintings & Draws'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.875
  lightness: 0.5625
  saturation: 0.9375
  rhythmicContrast: 0.7342031192965806
purpose: []
